import os
import base64
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_medical_report(patient_name: str, patient_data: dict, clinical_res: dict, rl_recs: dict, image_res: dict):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    
    h2 = styles['Heading2']
    h3 = styles['Heading3']
    normal = styles['Normal']
    
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], textColor=colors.red, fontSize=8)

    elements = []
    
    # Header
    elements.append(Paragraph("AI-Powered Medical Assessment Report", title_style))
    elements.append(Spacer(1, 12))
    
    # Patient details
    lh = patient_data.get('lh', 0)
    fsh = patient_data.get('fsh', 0)
    lh_fsh_ratio = (lh / fsh) if fsh > 0 else 1.0
    
    patient_info = [
        ["Patient Name", patient_name],
        ["Patient ID", str(patient_data.get('patient_id', 'N/A'))],
        ["Age", str(patient_data.get('age', 'N/A'))],
        ["BMI", f"{clinical_res.get('calculated_bmi', 0):.2f}"],
        ["LH / FSH Ratio", f"{lh_fsh_ratio:.2f}"],
        ["Testosterone", f"{patient_data.get('testosterone', 'N/A')} ng/dL"],
        ["Thyroid History", "Yes" if patient_data.get('thyroid_history') else "No"]
    ]
    t1 = Table(patient_info, colWidths=[150, 300])
    t1.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.lightgrey),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey)
    ]))
    elements.append(t1)
    elements.append(Spacer(1, 12))
    
    # Clinical Predictions
    elements.append(Paragraph("2. Clinical & AI Predictions", h2))
    
    # ── Embed Ultrasound Image ──
    img_b64 = patient_data.get('ultrasound_base64')
    if img_b64:
        try:
            # Handle data URI prefix if present
            if "," in img_b64:
                img_b64 = img_b64.split(",")[1]
            img_data = base64.b64decode(img_b64)
            # Use ReportLab's built-in Image platypus flowable
            from reportlab.platypus import Image as RLImage
            img = RLImage(BytesIO(img_data), width=280, height=210)
            elements.append(img)
            elements.append(Spacer(1, 12))
        except Exception as e:
            print(f"[PDF_GEN] Error embedding image: {e}")

    top_rf = image_res.get('top_risk_factors', [])
    top_rf_str = ", ".join([f"{r['feature']} ({r['importance']*100:.0f}%)" for r in top_rf]) if top_rf else "N/A"

    pred_info = [
        ["PCOS Cysts Detected", "Yes" if image_res.get('cysts_detected') else "No"],
        ["PCOS Probability", f"{image_res.get('pcos_probability', 0)*100:.1f}%"],
        ["Top Risk Factors", top_rf_str],
        ["Temporal Trend", f"{image_res.get('temporal_risk', 'Stable')} (Risk: {image_res.get('temporal_risk_score', 0)*100:.0f}%)"]
    ]
    t2 = Table(pred_info, colWidths=[150, 300])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.lightblue),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey)
    ]))
    elements.append(t2)
    elements.append(Spacer(1, 12))

    # Lifestyle Guidelines
    elements.append(Paragraph("3. Personalized Lifestyle Recommendations", h2))
    
    diet = rl_recs.get('diet', {})
    if diet:
        elements.append(Paragraph(f"<b>Diet Plan ({diet.get('title', '')}):</b> {diet.get('overview', '')}", normal))
        elements.append(Spacer(1, 6))
        
    exercise = rl_recs.get('exercise', {})
    if exercise:
        elements.append(Paragraph(f"<b>Exercise Routine ({exercise.get('title', '')}):</b> {exercise.get('overview', '')}", normal))
        elements.append(Spacer(1, 6))
        
    sleep = rl_recs.get('sleep', {})
    stress = rl_recs.get('stress_management', {})
    if sleep or stress:
        sleep_txt = f"Sleep: {sleep.get('schedule', '')} " if sleep else ""
        stress_txt = "Daily Practices: " + ", ".join(stress.get('daily_practices', [])) if stress else ""
        elements.append(Paragraph(f"<b>Sleep & Stress:</b> {sleep_txt} | {stress_txt}", normal))
        elements.append(Spacer(1, 6))
        
    medical = rl_recs.get('medical_advice', {})
    if medical:
        elements.append(Paragraph(f"<b>Medical Advice:</b> {medical.get('when_to_see_doctor', '')}", normal))
        elements.append(Spacer(1, 12))
    
    # Disclaimer
    elements.append(Spacer(1, 24))
    elements.append(Paragraph("MEDICAL DISCLAIMER: This report is generated by an Artificial Intelligence system and is intended for informational and decision-support purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of a qualified healthcare provider with any questions regarding medical conditions.", disclaimer_style))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer
